version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.20
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: Postgres_docker
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
       - checkout
       - run: node --version
       - run: npm install
       - run:
           command: npm run test
           name: Run tests
    # ... steps for building/testing app ...
       - setup_remote_docker:
           docker_layer_caching: true
       - run:
           name: install docker
           command: |
             set -x
             VER="20.10.14"
             curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
             tar -xz -C /tmp -f /tmp/docker-$VER.tgz
             mv /tmp/docker/* /usr/bin
       - run:
           name: Build docker
           command: npm run docker:build

workflows:
  version: 2
  build:
    jobs:
      - build